# Define the goal
#Header header
#string body
#uint32 semantic_motion_id  # Specify which dishwasher we want to use
#string semantic_motion_name
#string target_id
#string phrase
#float32 param1
#---
# Define the result
#uint32 semantic_motion_id
#uint32 status_code
#---
# Define a feedback message
#uint32 semantic_motion_id
#uint32 status_code

Header header
string motion_name
string phrase
string param
---
bool result
---