face_recognition:
  target_memory:      'social_events_memory'
  events:             ['face_recognized']
  data:
    face_id:          []
    person_id:        []
    name:             []
    confidence:       []
    count:            0

person_identification:
  target_memory:        'social_events_memory'
  events:             ['person_identified']
  data:
    session_face_id:  []
    person_id:        []
    name:             []
    face_pos:         []
    confidence:       []
    age:              []
    gender:           []
    cloth_color:      []
    eyeglasses:       []
    height:           []
    hair_style:       []
    emotion:          []         # 'happy', 'unhappy'
    count:            0

persons:
  target_memory: 'environmental_memory'
  events: []
  data:
    name: ''
    description: ''
    xyz: [0.0, 0.0, 0.0]  # Represents the x, y, z
    rpy: [0.0, 0.0, 0.0]  # Represents the fixed axis roll, pitch, yaw
    frame_id: 'world'     # frame_id
