  # 사람 검출/추적
  person_detection:
    target_memory: 'social_events_memory'
    events: ['person_appeared']
    data:
      person_id: []
      count: 0

  person_detection:
    target_memory: 'social_events_memory'
    events: ['person_disappeared']
    data:
      person_id: []
      count: 0

  face_detection:
    target_memory: 'social_events_memory'
    events: ['face_detected']
    data:
      face_id: []
      count: 0

  face_detection:
    target_memory: 'social_events_memory'
    events: ['face_disappeared']
    data:
      face_id: []
      count: 0

  face_recognition:
    target_memory: 'social_events_memory'
    events: ['face_recognized']
    data:
      face_id: []
      person_id: []
      name: []
      confidence: []
      count: 0

  facial_expression_recognition:
    target_memory: 'social_events_memory'
    events: ['facial_expression_detected']
    data:
      face_id: ''
      emotion_id: ''
      emotion_confidence: 0

  person_identification:
    target_memory: 'social_events_memory'
    events: ['person_identified']
    data:
      session_face_id: []
      person_id: []
      name: []
      face_pos: []
      confidence: []
      gender: []
      cloth_color: []
      eyeglasses: []
      height: []
      hair_style: []
      emotion: []         # 'happy', 'unhappy'
      count: 0

  # Person Idenficiation Information
  # retrieved from Episodic Memory
  memory_recall:
    target_memory: 'social_events_memory'
    events: ['memory_recalled']
    data:
      human_id: []  # current tracking id
      person_id: []
      name: []
      gender: []
      eyeglasses: []
      cloth_color: []
      hair_style: []
      confidence: []

  # Engagement Detection **
  engagement_detection:
    target_memory: 'social_events_memory'
    events: ['person_engaged']
    data:
      face_id: []
      count: 0

  # Disengagement Detection **
  engagement_detection:
    target_memory: 'social_events_memory'
    events: ['person_disengaged']
    data:
      face_id: []
      count: 0

  # 입술 움직임으로부터 판단한 발화 여부
  vad_by_lip_reading:
    target_memory: 'social_events_memory'
    events: ['lip_talking_started']
    data:
      face_id: ''

  vad_by_lip_reading:
    target_memory: 'social_events_memory'
    events: ['lip_talking_finished']
    data:
      face_id: ''

  # 의도인식
  intention_recognition:
    target_memory: 'social_events_memory'
    events: ['intention_affirmation']
    data:
      face_id: ''

  intention_recognition:
    target_memory: 'social_events_memory'
    events: ['intention_negation']
    data:
      face_id: ''

  intention_recognition:
    target_memory: 'social_events_memory'
    events: ['intention_concentration']
    data:
      face_id: ''

  people_detection:
    target_memory: 'social_events_memory'
    events: ['number_of_guests_changed']
    data:
      difference: 0
      no_of_people: -1

  pointing_gesture_recognition:
    target_memory: 'social_events_memory'
    events: ['pointing_gesture_recognized']
    data:
      face_id: ''
      gesture_id: ''

  # Approach & Leave Status
  # - minsu(minsu@etri.re.kr)
  presence_detection:
    target_memory: 'social_events_memory'
    events: ['person_approached']
    data:
      face_id: []
      count: 0

  presence_detection:
    target_memory: 'social_events_memory'
    events: ['person_left']
    data:
      face_id: []
      count: 0

  # Proxemic Status
  # a list of face IDs with a corresponding zone ID
  # - minsu(minsu@etri.re.kr)
  presence_detection:
    target_memory: 'social_events_memory'
    events: ['person_entered_zone']
    data:
      face_id: []
      zone_id: []
      count: 0

  # Saliency Status
  # notify the most salient person
  saliency_detection:
    target_memory: 'social_events_memory'
    events: ['saliency_changed']
    data:
      face_id: ''
      saliency_value: 0
      face_index: -1

# Turn_Taking Status
  turn_taking_detection:
    target_memory: 'social_events_memory'
    events: ['turn_take_detected']
    data:
      face_id: ''
      #person_id: ''

  turn_taking_detection:
    target_memory: 'social_events_memory'
    events: ['turn_release_detected']
    data:
      face_id: ''
      #person_id: ''

  turn_taking_detection:
    target_memory: 'social_events_memory'
    events: ['turn_wait_detected']
    data:
      face_id: ''
      #person_id: ''

  turn_taking_detection:
    target_memory: 'social_events_memory'
    events: ['turn_hold_detected']
    data:
      face_id: ''
      #person_id: ''

  # Participant's Role
  role_detection:
    target_memory: 'social_events_memory'
    events: ['active_participant_detected']
    data:
      face_id: ''
      #person_id: ''

  # Participant's Role
  role_detection:
    target_memory: 'social_events_memory'
    events: ['addressee_detected']
    data:
      addressee_detected: false
      face_id: ''
      #person_id: ''

  # Robot Speaking Status
  robot_speaking_detection:
    target_memory: 'social_events_memory'
    events: ['robot_speaking_detected']
    data:
