

  pointing_gesture_recognition:
    target_memory: 'social_events_memory'
    events: ['pointing_gesture_recognized']
    data:
      face_id: ''
      gesture_id: ''

# Turn_Taking Status
  turn_taking_detection:
    target_memory: 'social_events_memory'
    events: ['turn_take_detected']
    data:
      face_id: ''
      #person_id: ''

  turn_taking_detection:
    target_memory: 'social_events_memory'
    events: ['turn_release_detected']
    data:
      face_id: ''
      #person_id: ''

  turn_taking_detection:
    target_memory: 'social_events_memory'
    events: ['turn_wait_detected']
    data:
      face_id: ''
      #person_id: ''

  turn_taking_detection:
    target_memory: 'social_events_memory'
    events: ['turn_hold_detected']
    data:
      face_id: ''
      #person_id: ''

  # Participant's Role
  role_detection:
    target_memory: 'social_events_memory'
    events: ['active_participant_detected']
    data:
      face_id: ''
      #person_id: ''

  # Participant's Role
  role_detection:
    target_memory: 'social_events_memory'
    events: ['addressee_detected']
    data:
      addressee_detected: false
      face_id: ''
      #person_id: ''

  # Robot Speaking Status
  robot_speaking_detection:
    target_memory: 'social_events_memory'
    events: ['robot_speaking_detected']
    data:
